apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: parksmap-app
  template: parksmap-app
metadata:
  name: parksmap-app
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: "${SERVICE_NAME}"
      template: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: "${SERVICE_NAME}"
      weight: 100
    wildcardPolicy: None
parameters:
- description: The name of the service
  displayName: Service Name
  name: SERVICE_NAME
  value: "parksmap"