apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: parksmap-binary-template
metadata:
  name: parksmap-binary-template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: parksmap
    name: parksmap
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: parksmap
    name: parksmap
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: parksmap-binary
    name: parksmap-binary
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: parksmap:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5