---
- name: "Look up Nexus URL"
  command: >
    oc get route nexus -n {{ nexus_namespace }} -o custom-columns=ROUTE:.spec.host --no-headers
  register: nexus_url_result

- name: "Check nexus listening on http://{{ nexus_url_result.stdout }}"
  uri: 
    url: "http://{{ nexus_url_result.stdout }}"
    method: GET
    status_code: 200
    headers:
      Authorization: "Basic YWRtaW46YWRtaW4xMjM="
  retries: 180
  delay: 5
  register: nexus_result
  until: nexus_result is not failed
  changed_when: false